stages:
- name: build
  steps:
  - runScriptConfig:
      image: java:8
      shellScript: 'jar -cvf tracking.war *  '
- name: push
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: tracking:latest
      registry: index.docker.io
- name: deployment
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
