apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: tracking-deployment
  labels:
    app: tracking
spec:
  selector:
    matchLabels:
      app: tracking-app
  replicas: 1
  template:
    metadata:
      labels:
        app: tracking-app
    spec:
      imagePullSecrets:
        - name: pipeline-docker-registry
      containers:
      - name: tracking
        image: ${CICD_IMAGE}:test
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 8080