apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: tracking-deployment
  labels:
    app: tracking
spec:
  selector:
    matchLabels:
      app: tracking-app
  replicas: 1
  template:
    metadata:
      labels:
        app: tracking-app
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: tracking
        image: ${CICD_IMAGE}:latest
        ports:
        - containerPort: 8080
          hostIP: 52.166.205.79
          hostPort: 8080
          name: 8080tcp80800
          protocol: TCP
        - containerPort: 4848
          hostIP: 52.166.205.79
          hostPort: 4848
          name: 4848tcp4848
          protocol: TCP