version: "3.1"
services:

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tracking
    ports:
      - 6000:5432
  tracking:
    image: redxice/payara:$BRANCH_NAME
    ports:
      - 9060:8080
      - 4849:4848